### ISSUE TITLE
Question: html-loader打包的疑惑

### ISSUE THREAD

**Issue by blankzust** [lagoufed/fed-e-readme#2]
## 正在学习的内容

Webpack原理与实践 第三讲loader
最后两个例子：多个 Loader 的配合
```js
// ./markdown-loader.js
const marked = require('marked')

module.exports = source => {
  // 1. 将 markdown 转换为 html 字符串
  const html = marked(source)
  return html
}
```
```js
// ./webpack.config.js
module.exports = {
  entry: './src/main.js',
  output: {
    filename: 'bundle.js',
  },
  module: {
    rules: [
      {
        test: /\.md$/,
        use: [
          'html-loader',
          './markdown-loader'
        ]
      }
    ]
  }
}
```
## 遇到的问题
上诉例子打包结果
![image](https://user-images.githubusercontent.com/8541906/81393499-0d51d000-9153-11ea-9859-9b3c1942c060.png)
我很疑惑为什么多出一个export default，这里应该是html-loader做的转换，这样做有什么意义？loader最终产生的是webpack require函数的一个函数入参（字符串转换而来的），html-loader产生的函数返回值为啥不是一个简单的html字符串，而是一段js?

## 你目前的状态

工作4年，但是webpack只懂皮毛

## 额外的描述

我第一次提问，还望海涵。

**Comment by zce** [comment]
是否可以提交一个出现错误的用例，CodeSandbox 或者是的 GitHub 仓库

**Comment by zce** [comment]
我最后用 html-loader 配合我们自己的 markdown-loader 的原因有两点：

1. 希望让你了解 loader 之间如何配合工作，也就是 loader 管道概念（学习角度）
2. 尽可能让每一个模块的功能更简单，职责更单一，这是开发过程中的一个基本原则（开发角度）

**Comment by blankzust** [comment]
https://github.com/blankzust/webpack-demo/tree/master/webpack-loader

**Comment by blankzust** [comment]
> 我最后用 html-loader 配合我们自己的 markdown-loader 的原因有两点：
> 
> 1. 希望让你了解 loader 之间如何配合工作，也就是 loader 管道概念（学习角度）
> 2. 尽可能让每一个模块的功能更简单，职责更单一，这是开发过程中的一个基本原则（开发角度）
没有html-loader的时候，markdown-loader返回的字符串是有语法错误的，因为单纯的html字符串是无法eval()的，所以html-loader起到了将html字符串转换为可执行js的过程，这个在倒数第二个例子中，是这样写的：
```js
const marked = require('marked')

module.exports = src => {
  const htmlStr = marked(src);
  const code = `export default ${JSON.stringify(htmlStr)}`
  return code;
}
```
但是发现html-loader好像多做了一些转换，这些转换能否提点一番含义？

**Comment by zce** [comment]
核心问题：

https://github.com/blankzust/webpack-demo/blob/970af44d97c74ff6ebd0d204f65b61a749ecf1a8/webpack-loader/webpack.config.js#L23-L39

问题的原因是，你想同时尝试两种方式，而第二种方式中，你应该配置 index2.js

```javascript
module.exports = {
  // ....
  module: {
    rules: [
      {
        test: /demo\.md$/,
        use: [
          './index.js'
        ]
      },
      {
        test: /demo2\.md$/,
        use: [
          'html-loader',
          './index2.js' // 这个 loader 中返回的才是 HTML 字符串，需要 html-loader 继续处理
        ]
      }
    ]
  }
}

**Comment by blankzust** [comment]
噢，粗心了

**Comment by blankzust** [comment]
谢谢老师
