### ISSUE TITLE
Bug: 参数默认值不一定要在最后

### ISSUE THREAD

**Issue by functionwell** [lagoufed/fed-e-readme#3]
## 错误内容链接

https://kaiwu.lagou.com/xunlianying/index.html?courseId=17#/detail?weekId=741&lessonId=1471

## 错误描述

ES2015 参数默认值 章节，函数默认值可以出现在参数任意位置，不是必须在最后

## 预期结果

ES2015 参数默认值 章节，函数默认值可以出现在参数任意位置，不是必须在最后

## 额外的描述

ES2015 参数默认值 章节，函数默认值可以出现在参数任意位置，不是必须在最后

**Comment by zce** [comment]
已经收到，非常感谢你的指出。

的确是我说法上的不严谨，给你造成的困扰，深表歉意。

确实，语法角度上来说，这并不是必须的。

我当时想表达的意思是，默认参数建议放在最后，否则多个参数情况下，默认参数的作用无法最大程度的发挥。

我会尽快做出调整，更新上去的。
