### ISSUE TITLE
Question: Promise.resolve对接第三方Promise会加入到微任务队列中吗？

### ISSUE THREAD

**Issue by blankzust** [lagoufed/fed-e-readme#4]
## 正在学习的内容

Promise 静态方法：https://kaiwu.lagou.com/xunlianying/index.html?courseId=17#/detail?weekId=741&lessonId=1525

## 遇到的问题

里面有一段说可以通过Promise.resolve来引入第三方Promise，比如说bluebird，这样的第三方Promise会加入到microsoft queue里面吗？

**Comment by zce** [comment]
Bluebrid 作为 Promise 的兼容方案，是无法实现微任务的。

因为微任务是底层实现，JavaScript 层面无法实现。
