### ISSUE TITLE
Question: 最优循环自我验证结果和视频验证结果不同

### ISSUE THREAD

**Issue by blankzust** [lagoufed/fed-e-readme#5]
## 正在学习的内容
选择最优的循环
https://kaiwu.lagou.com/xunlianying/index.html?courseId=17#/detail?weekId=765&lessonId=2306

## 遇到的问题

自己通过js时间验证的结果和视频结果不同

```js
var arr = Array.from({ length: 100 }).map((item, index) => index)

function forTimes (arr) {
  const time = new Date().getTime()
  for (let i = 0; i < arr.length; i++) {
    console.log(arr[i])
  }
  const lastTime = new Date().getTime() - time
  console.log('for====  ' + lastTime)
  return lastTime
}

function forInTimes (arr) {
  const time = new Date().getTime()
  for (let i in arr) {
    console.log(arr[i])
  }
  const lastTime = new Date().getTime() - time
  console.log('forIn====  ' + lastTime)
  return lastTime
}
function forofTimes (arr) {
  const time = new Date().getTime()
  for (let item of arr) {
    console.log(item)
  }
  const lastTime = new Date().getTime() - time
  console.log('forOf====  ' + lastTime)
  return lastTime
}

function forEachTimes (arr) {
  const time = new Date().getTime()
  arr.forEach((item) => {
    console.log(item)
  })
  const lastTime = new Date().getTime() - time
  console.log('forEach====  ' + lastTime)
  return lastTime
}

function mapTimes (arr) {
  const time = new Date().getTime()
  arr.map((item) => {
    console.log(item)
  })
  const lastTime = new Date().getTime() - time
  console.log('map====  ' + lastTime)
  return lastTime
}

var a = forTimes(arr)
var b = forInTimes(arr)
var c = forEachTimes(arr)
var d = forofTimes(arr)
var e = mapTimes(arr)

console.log('for:' + a + '  forIn:' + b + '   forEach:' + c + '  forOf:' + d + '  mapTimes:' + e)

```
打印结果：
![image](https://user-images.githubusercontent.com/8541906/85354439-25cc4d00-b53d-11ea-9a7b-538637a018ab.png)

**Comment by blankzust** [comment]
视频中说是forEach最快，但是自我验证forEach最慢

**Comment by yyshi** [comment]
#### 代码执行验证：

当前执行结果与平台和环境有关，建议采用 console.time() 的方式测试代码运行时间，测试时也要尽可能多的取样，将你的代码在不同的平台环境下进行了测试

#### 01 Chrome ：

- 版本： 83.0. x  [win 64 位]
- 多次运行结果 ：
  - `for:57  forIn:46   forEach:47  forOf:43  mapTimes:47`  
  - `for:6  forIn:5   forEach:5  forOf:5  mapTimes:5`
  - `for:736  forIn:589   forEach:599  forOf:481  mapTimes:516`

#### 02 Firefox ：

- 版本：71.0  [win 64 位]
- 多次运行结果：
  -  ` for:15  forIn:10   forEach:12  forOf:9  mapTimes:9 `  
  - `  for:148  forIn:130   forEach:114  forOf:91  mapTimes:103 `
  - ` for:1585  forIn:1282   forEach:1080  forOf:785  mapTimes:857 `
- 一直都是 foreach 更快

#### 03 Node.js：

- 版本： 13.0  [win 64 位]
- 多次运行结果： 
  - `for:67  forIn:51   forEach:51  forOf:51  mapTimes:49` 
  - `for:469  forIn:429   forEach:383  forOf:393  mapTimes:354`
-  一直都是 foreach 更快

> 总结：
> 1. Friefox 与 Node 下 一直都是 forEach 更快
> 2. 不同版本的 Chrome 下多次运行之后偶尔会出现 for 和 foreach 接近的情况

**Comment by zce** [comment]
建议放大测试用例，多次测试取平均

**Comment by blankzust** [comment]
赞，这方面的循环语法，性能考虑的应该不是很多，感谢老师的严谨回复
